runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: src.main.app

libraries:
- name: ssl
  version: latest

env_variables:
  FIREBASE_PROJECT_ID: 'INSERT_FIREBASE_PROJECT_ID_HERE'